# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: seeder
  pool: 5
  username: seeder
  password: password
  host: localhost
  timeout: 5000

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: seeder
#   pool: 5
#   username: wisr
#   password: password
#   host: localhost
#   timeout: 5000  